[firebase]
apiKey: "AIzaSyChKkEJ78vAyjPgAUMcKV0IEF-DZGVuGvQ",
authDomain: "gatemark-d7fcf.firebaseapp.com",
projectId: "gatemark-d7fcf",
storageBucket: "gatemark-d7fcf.firebasestorage.app",
messagingSenderId: "917831094385",
appId: "1:917831094385:web:3153651f369ced2a5fcbd0",
measurementId: "G-HH07B5L74P"